apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage_test
  annotations:
    github.com/project-slug: apeng24/backstage_test
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: guests
